<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>S3Explorer</AssemblyName>
    <RootNamespace>S3Explorer.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\S3Explorer.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\S3Explorer.Core\S3Explorer.Core.csproj" />
    <ProjectReference Include="..\S3Explorer.Infrastructure.Cdn\S3Explorer.Infrastructure.Cdn.csproj" />
    <ProjectReference Include="..\S3Explorer.Infrastructure.S3\S3Explorer.Infrastructure.S3.csproj" />
  </ItemGroup>
</Project>
