<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>S3Explorer.Infrastructure.S3</AssemblyName>
    <RootNamespace>S3Explorer.Infrastructure.S3</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\S3Explorer.Core\S3Explorer.Core.csproj" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.511.8" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
  </ItemGroup>
</Project>
